#!/bin/sh

# 检查 package-lock.json 是否发生变化
if git diff --name-only HEAD@{1} HEAD | grep -E 'package-lock.json'; then
  echo "Detected changes in dependencies, running npm install..."
  npm install
else
  echo "No dependency changes detected, skipping npm install."
fi
